using UnityEngine;

/// <summary>
/// A chapter's shared difficulty curve. A level whose authored wave list is empty and whose
/// <c>waveCurve</c> points here has its waves generated by <see cref="WaveCurveExpander"/>
/// against its own allowedCharacters and allowedEnemyTypes, so the roster is written once on the
/// level and never restated per wave.
///
/// The numbers live in <see cref="WaveCurveShape"/>; this asset only carries them. Curve_Ugat is
/// seeded from Level 1's authored waves and WaveCurveGoldenTests holds it to that.
/// </summary>
[CreateAssetMenu(fileName = "Curve_", menuName = "Salinlahi/Wave Curve")]
public class WaveCurveSO : ScriptableObject
{
    [Tooltip("Total waves generated. 1 = opening wave only.")]
    [Min(1)] public int waveCount = 5;

    [Header("Opening wave")]
    [Min(1)] public int openingEnemyCount = 2;
    [Min(0.1f)] public float openingSpawnInterval = 6f;
    [Min(0f)] public float openingWaveStartDelay = 3f;

    [Header("Ramp (waves 2 to waveCount, linear)")]
    [Min(1)] public int rampFirstEnemyCount = 4;
    [Min(1)] public int rampLastEnemyCount = 7;
    [Min(0.1f)] public float rampFirstSpawnInterval = 5f;
    [Min(0.1f)] public float rampLastSpawnInterval = 3.5f;
    [Min(0f)] public float rampWaveStartDelay = 2f;

    public WaveCurveShape ToShape()
    {
        return new WaveCurveShape
        {
            WaveCount = waveCount,
            OpeningEnemyCount = openingEnemyCount,
            OpeningSpawnInterval = openingSpawnInterval,
            OpeningWaveStartDelay = openingWaveStartDelay,
            RampFirstEnemyCount = rampFirstEnemyCount,
            RampLastEnemyCount = rampLastEnemyCount,
            RampFirstSpawnInterval = rampFirstSpawnInterval,
            RampLastSpawnInterval = rampLastSpawnInterval,
            RampWaveStartDelay = rampWaveStartDelay,
        };
    }
}
